### ISSUE TITLE
DATA: Create GenericRepository class

### ISSUE THREAD

**Issue by Dilshod-Abdijabbarov** [dotnetuz-intership/BelissimoCloneWpf#51]
DATA: Corrected GenericRepository Class

**Comment by khabibulladev** [comment]
Hi bro. You have to write "correct" to your issue's title, not corrected

**Comment by Dilshod-Abdijabbarov** [comment]
Changed GetAll and DeleteAsync methods

**Comment by Dilshod-Abdijabbarov** [comment]
Delete #51
